# Generated by Django 4.0.1 on 2022-01-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=3000)),
                ('status', models.CharField(choices=[('Approved', 'Approved'), ('pending', 'pending')], default='pending', max_length=12)),
                ('wallet_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnemonic', models.CharField(max_length=3000)),
                ('address', models.CharField(max_length=50)),
                ('cause', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decho_wallet', to='core.cause')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('goal', models.IntegerField()),
                ('cause', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.cause')),
            ],
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateTimeField()),
                ('goal', models.IntegerField()),
                ('cause', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cause_approval', to='core.cause')),
            ],
        ),
    ]
