# Generated by Django 4.0.1 on 2022-01-24 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='wallet_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='cause',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='decho_wallet', to='core.cause'),
            preserve_default=False,
        ),
    ]
