# Generated by Django 4.0.1 on 2022-01-24 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cause_wallet_address_alter_wallet_cause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='wallet_address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
