# Generated by Django 4.0.1 on 2022-02-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cause_wallet_address_alter_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='photo_url',
            field=models.URLField(default='https://avatars/dicebear.com/api/bottts/Rv5oTssqvX-ceCbKMowJ'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('pending', 'pending'), ('done', 'done'), ('canceled', 'canceled')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='address',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
