# Generated by Django 4.0.1 on 2022-02-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cause_photo_url_alter_cause_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='photo_url',
            field=models.URLField(default='https://avatars/dicebear.com/api/bottts/6u6eD_gTw1byhiA7WZ8F'),
        ),
    ]
