# Generated by Django 4.0.1 on 2022-02-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cause_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='photo_url',
            field=models.URLField(default='https://avatars.dicebear.com/api/bottts/jsl1rfR4u3Q1H11_yw5u'),
        ),
    ]
