# Generated by Django 4.0.1 on 2022-02-18 15:20

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cause_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='photo_url',
            field=models.URLField(default=core.utils.gen_random_photo_url),
        ),
    ]
