# Generated by Django 4.0.1 on 2022-03-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_change_default_for_photo_url_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='cause',
            name='website_uri',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
