# Generated by Django 4.0.1 on 2022-03-30 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_giveaway'),
        ('core', '0009_remove_cause_website_uri'),
    ]

    operations = [
    ]
